version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/' # Location of package manifests
    schedule:
      day: "sunday"
      interval: 'weekly'
      time: "05:00"
      timezone: "America/Toronto"
    open-pull-requests-limit: 5
