env: standard
runtime: nodejs16
service: default

automatic_scaling:
  max_instances: 2

handlers:
  # All paths with extension to static file
  - url: /(.*\..+)$
    secure: always
    static_files: out/\1
    upload: out/(.*\..+)$

  # All paths routes to index page
  - url: /.*
    secure: always
    static_files: out/index.html
    upload: out/index.html
