/* AUTO GENERATED FILE. DO NOT MODIFY !!! */

export enum CypressIds {
  MODAL_APPOINTMENTS_ADD_DESCRIPTION = 'modal.appointments.add.description',
  MODAL_APPOINTMENTS_ADD_DATE_AND_START_TIME = 'modal.appointments.add.date.and.start.time',
  MODAL_APPOINTMENTS_ADD_SELECT_PATIENT = 'modal.appointments.add.select.patient',
  MODAL_APPOINTMENTS_ADD_SELECT_SERVICE_TYPE = 'modal.appointments.add.select.service.type',
  MODAL_APPOINTMENTS_ADD_BUTTON_ADD = 'modal.appointments.add.button.add',
  MODAL_APPOINTMENTS_ADD_CLOSE_ICON = 'modal.appointments.add.close.icon',
  MODAL_APPOINTMENTS_CONFIRM_CANCEL_SELECT_REASON = 'modal.appointments.confirm.cancel.select.reason',
  MODAL_APPOINTMENTS_CONFIRM_CANCEL_BUTTON_CONFIRM = 'modal.appointments.confirm.cancel.button.confirm',
  MODAL_APPOINTMENTS_EDIT_BUTTON_CANCEL = 'modal.appointments.edit.button.cancel',
  MODAL_APPOINTMENTS_EDIT_BUTTON_SAVE = 'modal.appointments.edit.button.save',
  MODAL_APPOINTMENTS_EDIT_DESCRIPTION = 'modal.appointments.edit.description',
  MODAL_APPOINTMENTS_EDIT_TIME_PICKER = 'modal.appointments.edit.time.picker',
  MODAL_APPOINTMENTS_EDIT_SELECT_SERVICE_TYPE = 'modal.appointments.edit.select.service.type',
  MODAL_APPOINTMENTS_EDIT_BUTTON_STATUS = 'modal.appointments.edit.button.status',
  MODAL_APPOINTMENTS_EDIT_CLOSE_ICON = 'modal.appointments.edit.close.icon',
  MODAL_APPOINTMENTS_CANCEL_CLOSE_ICON = 'modal.appointments.cancel.close.icon',
  PAGE_APPOINTMENTS_BUTTON_NEW_CALENDAR = 'page.appointments.button.new.calendar',
  PAGE_APPOINTMENTS_BUTTON_NEW_APPOINTMENT = 'page.appointments.button.new.appointment',
  PAGE_APPOINTMENTS_TITLE = 'page.appointments.title',
  PAGE_APPOINTMENTS_BUTTON_TODAY = 'page.appointments.button.today',
  PAGE_APPOINTMENTS_DESKTOP_DATE_PICKER = 'page.appointments.desktop.date.picker',
  PAGE_APPOINTMENTS_SELECT_RESOURCE = 'page.appointments.select.resource',
  COMMON_TIME_PICKER_BUTTON_SAVE = 'common.time.picker.button.save',
  COMMON_TIME_PICKER_BUTTON_CANCEL = 'common.time.picker.button.cancel',
  PAGE_SCHEDULING_TEMPLATES_BUTTON_CREATE = 'page.scheduling.templates.button.create',
  PAGE_SCHEDULING_TEMPLATES_BUTTON_DELETE = 'schedule.templates.delete.icon',
  PAGE_SCHEDULING_TEMPLATES_CHECKBOX_SELECT_ALL = 'page.scheduling.templates.checkbox.select.all',
  PAGE_SCHEDULING_TEMPLATES_CHECKBOX_SELECT = 'page.scheduling.templates.checkbox.select',
  PAGE_SCHEDULING_TEMPLATES_VISIBILITY_ICON = 'page.scheduling.templates.visibility.icon',
  PAGE_SCHEDULING_TEMPLATES_EDIT_ICON = 'page.scheduling.templates.edit.icon',
  PAGE_SCHEDULING_CREATE_TEMPLATES_NAME = 'page.scheduling.create.templates.name',
  PAGE_SCHEDULING_CREATE_TEMPLATES_CHECKBOX_WEEKDAYS = 'page.scheduling.create.templates.checkbox.weekdays',
  PAGE_SCHEDULING_CREATE_TEMPLATES_START = 'page.scheduling.create.templates.start',
  PAGE_SCHEDULING_CREATE_TEMPLATES_END = 'page.scheduling.create.templates.end',
  PAGE_SCHEDULING_CREATE_TEMPLATES_SERVICE_TYPE = 'page.scheduling.create.templates.service.type',
  PAGE_SCHEDULING_CREATE_TEMPLATES_BLOCK = 'page.scheduling.create.templates.block',
  PAGE_SCHEDULING_CREATE_TEMPLATES_SERVICE_TYPES = 'page.scheduling.create.templates.service.types',
  PAGE_SCHEDULING_CREATE_TEMPLATES_PLACEHOLDER = 'page.scheduling.create.templates.placeholder',
  PAGE_SCHEDULING_CREATE_TEMPLATES_BUTTON_CANCEL = 'page.scheduling.create.templates.button.cancel',
  PAGE_SCHEDULING_CREATE_TEMPLATES_BUTTON_SAVE = 'page.scheduling.create.templates.button.save',
  PAGE_SCHEDULING_CREATE_TEMPLATES_BUTTON_PLUS = 'page.scheduling.create.templates.button.plus',
  PAGE_SCHEDULING_APPLY_RESOURCE = 'page.scheduling.apply.resource',
  PAGE_SCHEDULING_APPLY_TEMPLATE = 'page.scheduling.apply.template',
  PAGE_SCHEDULING_APPLY_EVERY = 'page.scheduling.apply.every',
  PAGE_SCHEDULING_APPLY_DATE_START = 'page.scheduling.apply.date.start',
  PAGE_SCHEDULING_APPLY_DATE_END = 'page.scheduling.apply.date.end',
  PAGE_SCHEDULING_APPLY_BUTTON_APPLY = 'page.scheduling.apply.button.apply',
  PAGE_SCHEDULING_BLOCK_RESOURCE = 'page.scheduling.block.resource',
  PAGE_SCHEDULING_BLOCK_DATE_START = 'page.scheduling.block.date.start',
  PAGE_SCHEDULING_BLOCK_DATE_END = 'page.scheduling.block.date.end',
  PAGE_SCHEDULING_BLOCK_PLACEHOLDER = 'page.scheduling.block.placeholder',
  PAGE_SCHEDULING_BLOCK_BUTTON_APPLY = 'page.scheduling.block.button.apply'
}

/* AUTO GENERATED FILE. DO NOT MODIFY !!! */
