name: 'e2e tests processing'
inputs:
  node_version:
    description: 'Node version'
    required: false
    default: v16.13.0
  pat_to_read_package:
    description: 'Pat to read Packages'
    required: true

description: 'e2e test action'
runs:
  using: 'composite'
  steps:
    - name: Install Modules
      run: |
        echo "::group::Activate NodeJs version manager and install version"
        export NVM_DIR=~/.nvm
        source ~/.nvm/nvm.sh
        nvm install ${{ inputs.node_version }}
        nvm use ${{ inputs.node_version }}
        echo "::endgroup::"

        echo "::group::Install yarn modules"
        yarn install --ignore-scripts
        echo "::endgroup::"
      shell: bash

    - name: Static code analysis and build
      run: |
        echo "::group::Run Eslint"
        yarn run lint
        echo "::endgroup::"

        echo "::group::Build"
        yarn build
        echo "::endgroup::"
      shell: bash

    - name: Define Deployment Variables
      run: |
        echo "::group::Define Deployment Variables"
        echo "Use DEV service account"
        echo "PROJECT_ID=${{ env.dev_project_id }}" > $GITHUB_ENV
        echo "ENV_SERVICE_ACCOUNT=dev_service_account" >> $GITHUB_ENV
        echo "PROMOTEFLAG=--promote" >> $GITHUB_ENV
        echo "::endgroup::"
      shell: bash
