name: 'FE Validation'
inputs:
  node_version:
    description: 'Node version'
    required: false
    default: v16.17.0

description: 'e2e test action'
runs:
  using: 'composite'
  steps:
    - name: Install Modules
      run: |
        echo "::group::Activate NVM and install NodeJS version"
        source ~/.nvm/nvm.sh
        nvm install ${{ inputs.node_version }}
        nvm use ${{ inputs.node_version }}
        PATH="$HOME/.yarn/bin:$PATH"
        
        yarnVersion=$(yarn --version)
        echo "Yarn Version Before Berry Switch: $yarnVersion"
        echo "::endgroup::"


        echo "::group::Install yarn modules"
        yarn set version berry
        rm -rf node_modules

        nodeVersion=$(node --version)
        echo "Node Version: $nodeVersion"
        
        yarnVersion=$(yarn --version)
        echo "Yarn Version After Berry Switch: $yarnVersion"

        yarn install --no-immutable
        yarn add cypress
        echo "::endgroup::"
        

        echo "::group::Run Eslint"
        yarn run lint
        echo "::endgroup::"


        echo "::group::Build"
        yarn run build
        echo "::endgroup::"
      shell: bash
