name: Continues Integration VM Cache Clean
on:
  workflow_dispatch:
  schedule:
    # EST: At 3:00 AM on Sundays
    - cron: '0 0 * * 0'

jobs:
  build:
    timeout-minutes: 60
    runs-on: self-hosted-fe-v2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: VM cache cleanup
        uses: ./.github/actions/ci-clear-cache
