name: Danger Validations

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize]

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - name: Check out actions
        uses: actions/checkout@v2

      - uses: danger/danger-js@9.1.6
        name: Danger
        env:
          DANGER_DISABLE_TRANSPILATION: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
