name: Deploy to GAE
on:
  push:
    branches:
      - master
      - release/*
  release:
    types:
      - prereleased
      - released
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: setup-nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
          registry-url: https://npm.pkg.github.com/
          scope: '@OWNER'

      - uses: ./.github/actions/deploy-gae
        name: Deploy to GAE
        env:
          dev_service_account: ${{ secrets.DEV_GAE_DEPLOY_SA_KEY }}
